### ISSUE TITLE
Installation or execution problem

### ISSUE THREAD

**Issue by aetasoul** [cloudsftp/reSnap#3]
Procedure:
* Usb connection to remarkable 2
* ssh connection to remarkable 2 on 10.11.99.1 (all ok)
* Cloned the repo and send lz4 and head to rm2
* `scp lz4.arm root@10.11.99.1:~/lz4 `
* `ssh root@10.11.99.1 'chmod +x ~/lz4`
* `scp head.arm root@10.11.99.1:~/head`
* `ssh root@10.11.99.1 'chmod +x ~/head`
* Connected to rm2 and checked the files lz4 and head are in the folder (all ok)
* Install all on my machine
* `apt install liblz4-tool` (all ok)
* `apt install ffmpeg` (all ok)
* `apt install feh` (all ok)
* Run sh script `chmod +x reSnap.sh` and `./reSnap.sh`
* SSH password request, I insert the correct password and the script loop on the password request

What can I do to make it work?

**Comment by cloudsftp** [comment]
The script executes multiple commands on the reMarkable via ssh. That's why you get the impression that it loops on the password request.

To avoid retyping the password every time make sure you add your ssh-public-key to your reMarkable.
[This tutorial](https://remarkablewiki.com/tech/ssh) walks you through creating ssh-keys and adding the public key to your reMarkable. If you already have SSH keys on your machine you can skip the "Setting up ssh-keys" part (check it by running `ls ~/.ssh` if there are files in there you already have ssh-keys).

**Comment by aetasoul** [comment]
Hi,
I seen the ssh-key but i'm not fully sure to not lose it, so I prefer to keep the password for now.
Anyway the screenshot is not taken from the rm2, no screen open and no file save



There is a debug mode where I can see what happend? Some logs?

**Comment by cloudsftp** [comment]
If you lose the ssh-key you can still connect with the password. I would strongly encourage it.

There is unfortunately no debug mode but you should see error messages if something goes wrong.
Can you post your output?

**Comment by aetasoul** [comment]
I'm now trying with the wifi IP:

![image](https://user-images.githubusercontent.com/15131692/116665482-207c3200-a99a-11eb-8a78-842c1ad6c170.png)

Let me try with the ssh-key

**Comment by cloudsftp** [comment]
Yeah, you have to type the password like 4-5 times if you don't use the ssh-keys.

**Comment by aetasoul** [comment]
oooh ok, so the password is required multiple times, ok now I understand what happend.
I'll add the ssh key as soon as possible

**Comment by aetasoul** [comment]
It perfectly works! Thank you!
