### ISSUE TITLE
feh ERROR: Can't open X display. It *is* running, yeah?

### ISSUE THREAD

**Issue by bekatom** [cloudsftp/reSnap#9]
I see error  ```feh ERROR: Can't open X display. It *is* running, yeah?```
Any help?

**Comment by bekatom** [comment]
While installing lz4 on remarkable I see this error 

```Job for rm2fb.service failed because the control process exited with error code.
See "systemctl status rm2fb.service" and "journalctl -xe" for details.
Collected errors:
 * pkg_run_script: package "display" postinst script returned status 1.
 * opkg_configure: display.postinst returned 1.
 ```
 
 I see rm2fb is missing, but after that, when I'm trying to install rm2fb
 
 I see rm2fb is missing from Toltec
 
 Any help?

**Comment by cloudsftp** [comment]
So my guess is that the two issues are not related.

For the first one there seems to be no X server running.
Are you using WSL? In that case you have to configure it to run GUIs first. https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
If not, you may be using Wayland instead of X11. In that case try another image viewer instead of `feh` that supports Wayland.

As for the second issue - I have no idea sorry.
